import buildingImgOne from "../../../../assets/images/building/building-img-1.png";
import buildingImgTwo from "../../../../assets/images/building/building-img-2.png";
import buildingImgThree from "../../../../assets/images/building/building-img-3.png";
import buildingImgFour from "../../../../assets/images/building/building-img-4.png";

const parkingFloorListData = [
  {
    _id: 1,
    buildingImages: [
      buildingImgOne,
      buildingImgTwo,
      buildingImgThree,
      buildingImgFour,
    ],
    buildingName: "Washington Square Parking",
    address: "1051 18th St NW, Washington, DC 20006",
    parkingTime: "24 hours CCTV and Parking Services",
    totalParkingSpace: "187",
    totalOccupiedSpace: "110",
    totalFreeSpace: "77",
    sensorIssue: "Ps-101,109,111",
    value: "36",
    color: "#18BC9C",
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 2,
    buildingImages: [
      buildingImgOne,
      buildingImgTwo,
      buildingImgThree,
      buildingImgFour,
    ],
    buildingName: "City Center Parking",
    address: "825 10th St NW, Washington, DC 20001",
    parkingTime: "24 hours monitored parking",
    totalParkingSpace: "250",
    totalOccupiedSpace: "150",
    totalFreeSpace: "100",
    sensorIssue: "Ps-201,203,205",
    value: "55",
    color: "#18BC9C",
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 3,
    buildingImages: [
      buildingImgOne,
      buildingImgTwo,
      buildingImgThree,
      buildingImgFour,
    ],
    buildingName: "Union Station Parking",
    address: "50 Massachusetts Ave NE, Washington, DC 20002",
    parkingTime: "Open 24/7 with security",
    totalParkingSpace: "300",
    totalOccupiedSpace: "180",
    totalFreeSpace: "120",
    sensorIssue: "Ps-301,303,305",
    value: "22",
    color: "#F12323",
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 4,
    buildingImages: [
      buildingImgOne,
      buildingImgTwo,
      buildingImgThree,
      buildingImgFour,
    ],
    buildingName: "National Gallery Parking",
    address: "600 Constitution Ave NW, Washington, DC 20565",
    parkingTime: "7 AM - 11 PM",
    totalParkingSpace: "200",
    totalOccupiedSpace: "90",
    totalFreeSpace: "110",
    sensorIssue: "Ps-401,403,405",
    value: "78",
    color: "#18BC9C",
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 5,
    buildingImages: [
      buildingImgOne,
      buildingImgTwo,
      buildingImgThree,
      buildingImgFour,
    ],
    buildingName: "The White House Parking",
    address: "1600 Pennsylvania Ave NW, Washington, DC 20500",
    parkingTime: "Restricted access parking",
    totalParkingSpace: "50",
    totalOccupiedSpace: "30",
    totalFreeSpace: "20",
    sensorIssue: "Ps-501,503",
    value: "17",
    color: "#F12323",
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
];
export { parkingFloorListData };
