import buildingImgOne from '../../../../assets/images/building/building-img-1.png';
import buildingImgTwo from '../../../../assets/images/building/building-img-2.png';
import buildingImgThree from '../../../../assets/images/building/building-img-3.png';
import buildingImgFour from '../../../../assets/images/building/building-img-4.png';
import {
  PerformanceIcon,
  FreeSpaceIcon,
  OccupiedParkingIcon,
  FloorNameIcon,
  CategoryIcon,
  AreaIcon,
} from '../../../../assets/svgs/Icon';

const buildingsManagersListData = [
  {
    _id: 1,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'Washington Square Parking',
    address: '1051 18th St NW, Washington, DC 20006',
    parkingTime: '24 hours CCTV and Parking Services',
    totalParkingSpace: '187',
    totalOccupiedSpace: '110',
    totalFreeSpace: '77',
    sensorIssue: 'Ps-101,109,111',
  },
];

const spacesCardsData = [
  {
    title: 'Performance',
    value: '27',
    description: 'Sales up 27% from last month.',
    color: '#18BC9C',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
    cardType: 'performance',
    icon: <PerformanceIcon />,
  },
  {
    title: 'Free Parking Space',
    value: '27',
    color: '#1B7AA6',
    description: 'Free parking space down 18% today.',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
    cardType: 'freeSpace',
    icon: <FreeSpaceIcon />,
  },
  {
    title: 'Occupied Space',
    value: '27',
    color: '#F39C11',
    description: 'Occupied space up 21% today.',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
    cardType: 'occupiedSpace',
    icon: <OccupiedParkingIcon />,
  },
  [
    {
      type: 'installed',
      count: 34,
    },
    { type: 'active', count: 34 },

    { type: 'offline', count: 55 },
  ],
];

const alertsData = [
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'attention',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'alert',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'notification',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'warning',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'warning',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'attention',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'notification',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'warning',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'warning',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'attention',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'notification',
    dateTime: 'July 30 09:30 AM',
  },
  {
    alert: 'A sensor is currently disconnected. Please check the device and reconnect.',
    alertType: 'attention',
    dateTime: 'July 30 09:30 AM',
  },
];

const parkingFloorListData = [
  {
    _id: 1,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'Washington Square Parking',
    address: '1051 18th St NW, Washington, DC 20006',
    parkingTime: '24 hours CCTV and Parking Services',
    totalParkingSpace: '187',
    totalOccupiedSpace: '110',
    totalFreeSpace: '77',
    sensorIssue: 'Ps-101,109,111',
    value: '36',
    color: '#18BC9C',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 2,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'City Center Parking',
    address: '825 10th St NW, Washington, DC 20001',
    parkingTime: '24 hours monitored parking',
    totalParkingSpace: '250',
    totalOccupiedSpace: '150',
    totalFreeSpace: '100',
    sensorIssue: 'Ps-201,203,205',
    value: '55',
    color: '#18BC9C',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 3,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'Union Station Parking',
    address: '50 Massachusetts Ave NE, Washington, DC 20002',
    parkingTime: 'Open 24/7 with security',
    totalParkingSpace: '300',
    totalOccupiedSpace: '180',
    totalFreeSpace: '120',
    sensorIssue: 'Ps-301,303,305',
    value: '22',
    color: '#F12323',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 4,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'National Gallery Parking',
    address: '600 Constitution Ave NW, Washington, DC 20565',
    parkingTime: '7 AM - 11 PM',
    totalParkingSpace: '200',
    totalOccupiedSpace: '90',
    totalFreeSpace: '110',
    sensorIssue: 'Ps-401,403,405',
    value: '78',
    color: '#18BC9C',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 5,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'The White House Parking',
    address: '1600 Pennsylvania Ave NW, Washington, DC 20500',
    parkingTime: 'Restricted access parking',
    totalParkingSpace: '50',
    totalOccupiedSpace: '30',
    totalFreeSpace: '20',
    sensorIssue: 'Ps-501,503',
    value: '17',
    color: '#F12323',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 6,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'Lincoln Memorial Parking',
    address: '2 Lincoln Memorial Cir NW, Washington, DC 20037',
    parkingTime: '8 AM - 8 PM',
    totalParkingSpace: '150',
    totalOccupiedSpace: '70',
    totalFreeSpace: '80',
    sensorIssue: 'Ps-601,603,605',
    value: '12',
    color: '#F12323',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 7,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'Capitol Building Parking',
    address: 'First St SE, Washington, DC 20004',
    parkingTime: '7 AM - 10 PM',
    totalParkingSpace: '200',
    totalOccupiedSpace: '140',
    totalFreeSpace: '60',
    sensorIssue: 'Ps-701,703,705',
    value: '36',
    color: '#18BC9C',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 8,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'Smithsonian National Air and Space Museum Parking',
    address: '600 Independence Ave SW, Washington, DC 20560',
    parkingTime: 'Open 24/7',
    totalParkingSpace: '300',
    totalOccupiedSpace: '200',
    totalFreeSpace: '100',
    sensorIssue: 'Ps-801,803,805',
    value: '27',
    color: '#F12323',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 9,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'Georgetown Waterfront Park Parking',
    address: '3303 Water St NW, Washington, DC 20007',
    parkingTime: '9 AM - 9 PM',
    totalParkingSpace: '120',
    totalOccupiedSpace: '60',
    totalFreeSpace: '60',
    sensorIssue: 'Ps-901,903,905',
    value: '40',
    color: '#18BC9C',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
  {
    _id: 10,
    buildingImages: [buildingImgOne, buildingImgTwo, buildingImgThree, buildingImgFour],
    buildingName: 'Arlington National Cemetery Parking',
    address: '1 Memorial Ave, Arlington, VA 22211',
    parkingTime: 'Open daily 8 AM - 5 PM',
    totalParkingSpace: '400',
    totalOccupiedSpace: '250',
    totalFreeSpace: '150',
    sensorIssue: 'Ps-1001,1003,1005',
    value: '09',
    color: '#F12323',
    data: [300, 23, 450, 220, 600, 230, 100, 50],
  },
];

const floorDetailsList = [
  {
    title: 'Floor Name',
    subtitle: 'Kode Building',
    icon: <FloorNameIcon />,
  },
  {
    title: 'Category',
    subtitle: 'Commercial',
    icon: <CategoryIcon />,
  },
  {
    title: 'Area',
    subtitle: '65,0000 SF',
    icon: <AreaIcon />,
  },
];

export { buildingsManagersListData, spacesCardsData, alertsData, parkingFloorListData, floorDetailsList };
